;    
;    PMDEmu - AVR based emulator of Czechoslovak microcomputer PMD-85 originally based on I8080
;    Copyright (C) 2003  Peter Chrenko <peto@kmit.sk>, J.Matusku 2178/21, 955 01 Topolcany, Slovakia
;
;    This program is free software; you can redistribute it and/or modify
;    it under the terms of the GNU General Public License as published by
;    the Free Software Foundation; either version 2 of the License, or
;    (at your option) any later version.
;
;    This program is distributed in the hope that it will be useful,
;    but WITHOUT ANY WARRANTY; without even the implied warranty of
;    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;    GNU General Public License for more details.
;
;    You should have received a copy of the GNU General Public License
;    along with this program; if not, write to the Free Software
;    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
;

		rjmp	_nop
		rjmp	_lxi_b
		rjmp	_stax_b
		rjmp	_inx_b
		rjmp	_inr_b
		rjmp	_dcr_b
		rjmp	_mvi_b
		rjmp	_rlca
		rjmp	_none
		rjmp	_dad_b
		rjmp	_ldax_b
		rjmp	_dcx_b
		rjmp	_inr_c
		rjmp	_dcr_c
		rjmp	_mvi_c
		rjmp	_rrca
		rjmp	_none
		rjmp	_lxi_d
		rjmp	_stax_d
		rjmp	_inx_d
		rjmp	_inr_d
		rjmp	_dcr_d
		rjmp	_mvi_d
		rjmp	_rla
		rjmp	_none
		rjmp	_dad_d
		rjmp	_ldax_d
		rjmp	_dcx_d
		rjmp	_inr_e
		rjmp	_dcr_e
		rjmp	_mvi_e
		rjmp	_rra
		rjmp	_none
		rjmp	_lxi_h
		rjmp	_shld
		rjmp	_inx_h
		rjmp	_inr_h
		rjmp	_dcr_h
		rjmp	_mvi_h
		rjmp	_daa
		rjmp	_none
		rjmp	_dad_h
		rjmp	_lhld
		rjmp	_dcx_h
		rjmp	_inr_l
		rjmp	_dcr_l
		rjmp	_mvi_l
		rjmp	_cma
		rjmp	_none
		rjmp	_lxi_sp
		rjmp	_sta
		rjmp	_inx_sp
		rjmp	_inr_m
		rjmp	_dcr_m
		rjmp	_mvi_m
		rjmp	_stc
		rjmp	_none
		rjmp	_dad_sp
		rjmp	_lda
		rjmp	_dcx_sp
		rjmp	_inr_a
		rjmp	_dcr_a
		rjmp	_mvi_a
		rjmp	_cmc
		rjmp	_mov_bb
		rjmp	_mov_bc
		rjmp	_mov_bd
		rjmp	_mov_be
		rjmp	_mov_bh
		rjmp	_mov_bl
		rjmp	_mov_bm
		rjmp	_mov_ba
		rjmp	_mov_cb
		rjmp	_mov_cc
		rjmp	_mov_cd
		rjmp	_mov_ce
		rjmp	_mov_ch
		rjmp	_mov_cl
		rjmp	_mov_cm
		rjmp	_mov_ca
		rjmp	_mov_db
		rjmp	_mov_dc
		rjmp	_mov_dd
		rjmp	_mov_de
		rjmp	_mov_dh
		rjmp	_mov_dl
		rjmp	_mov_dm
		rjmp	_mov_da
		rjmp	_mov_eb
		rjmp	_mov_ec
		rjmp	_mov_ed
		rjmp	_mov_ee
		rjmp	_mov_eh
		rjmp	_mov_el
		rjmp	_mov_em
		rjmp	_mov_ea
		rjmp	_mov_hb
		rjmp	_mov_hc
		rjmp	_mov_hd
		rjmp	_mov_he
		rjmp	_mov_hh
		rjmp	_mov_hl
		rjmp	_mov_hm
		rjmp	_mov_ha
		rjmp	_mov_lb
		rjmp	_mov_lc
		rjmp	_mov_ld
		rjmp	_mov_le
		rjmp	_mov_lh
		rjmp	_mov_ll
		rjmp	_mov_lm
		rjmp	_mov_la
		rjmp	_mov_mb
		rjmp	_mov_mc
		rjmp	_mov_md
		rjmp	_mov_me
		rjmp	_mov_mh
		rjmp	_mov_ml
		rjmp	_hlt
		rjmp	_mov_ma
		rjmp	_mov_ab
		rjmp	_mov_ac
		rjmp	_mov_ad
		rjmp	_mov_ae
		rjmp	_mov_ah
		rjmp	_mov_al
		rjmp	_mov_am
		rjmp	_mov_aa
		rjmp	_add_b
		rjmp	_add_c
		rjmp	_add_d
		rjmp	_add_e
		rjmp	_add_h
		rjmp	_add_l
		rjmp	_add_m
		rjmp	_add_a
		rjmp	_adc_b
		rjmp	_adc_c
		rjmp	_adc_d
		rjmp	_adc_e
		rjmp	_adc_h
		rjmp	_adc_l
		rjmp	_adc_m
		rjmp	_adc_a
		rjmp	_sub_b
		rjmp	_sub_c
		rjmp	_sub_d
		rjmp	_sub_e
		rjmp	_sub_h
		rjmp	_sub_l
		rjmp	_sub_m
		rjmp	_sub_a
		rjmp	_sbb_b
		rjmp	_sbb_c
		rjmp	_sbb_d
		rjmp	_sbb_e
		rjmp	_sbb_h
		rjmp	_sbb_l
		rjmp	_sbb_m
		rjmp	_sbb_a
		rjmp	_ana_b
		rjmp	_ana_c
		rjmp	_ana_d
		rjmp	_ana_e
		rjmp	_ana_h
		rjmp	_ana_l
		rjmp	_ana_m
		rjmp	_ana_a
		rjmp	_xra_b
		rjmp	_xra_c
		rjmp	_xra_d
		rjmp	_xra_e
		rjmp	_xra_h
		rjmp	_xra_l
		rjmp	_xra_m
		rjmp	_xra_a
		rjmp	_ora_b
		rjmp	_ora_c
		rjmp	_ora_d
		rjmp	_ora_e
		rjmp	_ora_h
		rjmp	_ora_l
		rjmp	_ora_m
		rjmp	_ora_a
		rjmp	_cmp_b
		rjmp	_cmp_c
		rjmp	_cmp_d
		rjmp	_cmp_e
		rjmp	_cmp_h
		rjmp	_cmp_l
		rjmp	_cmp_m
		rjmp	_cmp_a
		rjmp	_rnz
		rjmp	_pop_b
		rjmp	_jnz
		rjmp	_jmp
		rjmp	_cnz
		rjmp	_push_b
		rjmp	_adi
		rjmp	_rst0
		rjmp	_rz
		rjmp	_ret
		rjmp	_jz
		rjmp	_none
		rjmp	_cz
		rjmp	_call
		rjmp	_aci
		rjmp	_rst1
		rjmp	_rnc
		rjmp	_pop_d
		rjmp	_jnc
		rjmp	_out
		rjmp	_cnc
		rjmp	_push_d
		rjmp	_sui
		rjmp	_rst2
		rjmp	_rc
		rjmp	_none
		rjmp	_jc
		rjmp	_in
		rjmp	_cc
		rjmp	_none
		rjmp	_sbi
		rjmp	_rst3
		rjmp	_rpo
		rjmp	_pop_h
		rjmp	_jpo
		rjmp	_xthl
		rjmp	_cpo
		rjmp	_push_h
		rjmp	_ani
		rjmp	_rst4
		rjmp	_rpe
		rjmp	_pchl
		rjmp	_jpe
		rjmp	_xchg
		rjmp	_cpe
		rjmp	_none
		rjmp	_xri
		rjmp	_rst5
		rjmp	_rp
		rjmp	_pop_a
		rjmp	_jp
		rjmp	_di
		rjmp	_cp
		rjmp	_push_a
		rjmp	_ori
		rjmp	_rst6
		rjmp	_rm
		rjmp	_sphl
		rjmp	_jm
		rjmp	_ei
		rjmp	_cm
		rjmp	_none
		rjmp	_cpi
		rjmp	_rst7
